[build]
  command = "npm run build"
  publish = "out"
  # Define environment variables directly
  [build.environment]
    NODE_VERSION = "18"
    NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; unsafe-inline; unsafe-eval *.netlify.app; img-src 'self' data: blob: *.unsplash.com *.cosmedocs.com; font-src 'self' data: fonts.gstatic.com;"
